name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-04-09"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"			#d1数据库绑定名默认不可修改
database_name = "cloudmail"		#d1数据库名字
database_id = "b2f9bed6-1f0e-4a06-88b5-f0813d048eb4"		#d1数据库id

[[kv_namespaces]]
binding = "cloudmail"			#kv绑定名默认不可修改
id = "bfce5f540a4d4123a343de37ff920526"					#kv数据库id

[[r2_buckets]]
binding = "cloudmail"			#r2对象存储绑定名默认不可修改
bucket_name = "cloudmail"		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[vars]
orm_log = false
domain = ["selected.plus","mc2018.com","hexameter.cc"]				#邮件域名可可配置多个 示例: ["example1.com","example2.com"]
admin = "cmail@mc2018.com"				#管理员的邮箱	示例: admin@example.com
jwt_secret = "4423748504f01b08968f6cb324f6741bfbc02e9627bda4e0fa2a8afd04a12a3c6a5645ef45fad181d56fd668562ea84c"			#jwt令牌的密钥,随便填一串字符串
